network:
  num_leads: 1
  ### this part does not control builder/trainer
  text_model: ncbi/MedCPT-Query-Encoder
  free_layers: 6 # set 12 to freeze all layer in bert
  feature_dim: 768
  d_model: 512
  nheads: 2
  num_layers: 2

  projection_head:
    mlp_hidden_size: 128
    projection_size: 128

dataset:
  dataset_name: 'ed'

trainer:
  batch_size: 256
  val_batch_size: 8
  checkpoint_interval: 25
  max_epochs: 100
  num_workers: 0

optimizer:
  params:
    lr: 1.0e-3
    weight_decay: 1.0e-8