network:
  num_leads: 1
  ### this part does not control builder/trainer
  text_model: ncbi/MedCPT-Query-Encoder
  free_layers: 6 # set 12 to freeze all layer in bert
  feature_dim: 768
  d_model: 256
  nheads: 4
  num_layers: 3

  projection_head:
    mlp_hidden_size: 256
    projection_size: 256

dataset:
  dataset_name: 'mimic'

trainer:
  batch_size: 256
  val_batch_size: 16
  checkpoint_interval: 25
  max_epochs: 100
  num_workers: 0

optimizer:
  params:
    lr: 0.005
    weight_decay: 1.0e-8